name: iOS

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build-and-test:

    runs-on: macos-13

    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v3
    
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_15.0.1.app
      
    - name: Xcode version
      run: /usr/bin/xcodebuild -version
    
    - name: Build and test
      run: xcodebuild clean build test -project ThreatLevelMidnight.xcodeproj -scheme "ThreatLevelMidnight" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -skipPackagePluginValidation -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 15 Pro,OS=17.0.1" ONLY_ACTIVE_ARCH=YES
